### ISSUE TITLE
No "Use this template" button

### ISSUE THREAD

**Issue by lahuuki** [LieberInstitute/template_project#1]
The current github page doesn't align with "[Creating a repository from a template"](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) tutorial. The instructions to a "Use this template" button as the second step, and that seems to be missing from this page. 
![Screen Shot 2022-10-19 at 9 43 14 AM](https://user-images.githubusercontent.com/36641297/196715523-ac5c10b3-d0bc-4cf3-9a3f-5b96e2737cf1.png)

**Comment by lcolladotor** [comment]
Hmmm... I'll need help with this.

**Comment by gpertea** [comment]
Resolved - it was a checkbox in the repository settings that would make this available as a template.
